name: cinema_mobile
description: "Cinema mobile app (Flutter) — Authentication & User Profile."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2                    # เรียก REST API
  provider: ^6.1.2               # state management
  flutter_secure_storage: ^9.2.2 # เก็บ token อย่างปลอดภัย
  youtube_player_iframe: ^5.2.0  # เล่นตัวอย่างหนัง YouTube (บน web = iframe จริง)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
